server:
  port: 8089

spring:
  application:
    name: reto-tecnico-smart

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: wilmer
    password: admin123

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

custom-password:
  validation:
    regex: "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=!.])(?=\\S+$).{8,}$"

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
